myshop/cart/urls.py
from django.urls import path

from .views import *

app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', cart_add, name='cart_add'),
    path('dec/<int:product_id>/', cart_dec, name='cart_dec'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
]

myshop/coupons/urls.py
from django.urls import path

from .views import *

app_name = 'coupons'

urlpatterns = [
    path('apply/', coupon_apply, name='apply'),
]

myshop/myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _

urlpatterns = i18n_patterns(
    path(_('admin/'), admin.site.urls),
    path(_('cart/'), include('cart.urls', namespace='cart')),
    path(_('orders/'), include('orders.urls', namespace='orders')),
    path(_('payment/'), include('payment.urls', namespace='payment')),
    path(_('coupons/'), include('coupons.urls', namespace='coupons')),
    path('rosetta/', include('rosetta.urls')),
    path('', include('shop.urls', namespace='shop')),
)

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

myshop/orders/urls.py
from django.utils.translation import gettext_lazy as _
from django.urls import path
from .views import *

app_name = 'orders'

urlpatterns = [
    path(
        _('create/'), 
        order_create, 
        name='order_create'
    ),
    path(
        'admin/order/<int:order_id>/',
        admin_order_detail,
        name='admin_order_detail'
    ),
    path(
        'admin/order/<int:order_id>/pdf/',
        admin_order_pdf,
        name='admin_order_pdf'
    ),
]

myshop/shop/urls.py
from django.urls import path

from .views import *

app_name = 'shop'

urlpatterns = [
    path('', product_list, name='product_list'),
    path(
        '<slug:category_slug>/', 
        product_list, 
        name='product_list_by_category'
    ),
    path(
        '<int:id>/<slug:slug>/',
        product_detail,
        name='product_detail'
    ),
]

myshop/cart/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES,
        coerce=int,
        label=_('Quantity')
    )
    override = forms.BooleanField(
        required=False,
        initial=False,
        widget=forms.HiddenInput
    )

myshop/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST

from shop.models import Product
from coupons.forms import CouponApllyForm
from shop.recommender import Recommender

from .cart import Cart
from .forms import CartAddProductForm

# Create your views here.
@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(
        Product, id=product_id
    )
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(
            product=product,
            quantity=cd['quantity'],
            override_quantity=cd['override']
        )
    return redirect('cart:cart_detail')

@require_POST
def cart_dec(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(
        Product, id=product_id
    )
    cart.decrease(
        product=product,
        quantity = --1,
    )
    return redirect('cart:cart_detail')

@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(
        Product,
        id=product_id
    )
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    product = get_object_or_404(
        Product, id=1
    )
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
            initial={
                'quantity': item['quantity'],
                'override': True,
            }
        )
    coupon_apply_form = CouponApllyForm()
    r = Recommender()
    cart_products = [item['product'] for item in cart]
    if cart:
        recommended_products = r.suggest_products_for(cart_products, max_results=4)
    else:
        product = get_object_or_404(
                    Product, id=1
                    )
        cart_products = [product]
        recommended_products = r.suggest_products_for(cart_products, max_results=4)
    return render(
        request,
        'cart/detail.html',
        {
            'cart':cart,
            'coupon_apply_form': coupon_apply_form,
            'recommended_products': recommended_products
        }
    )

myshop/cart/templates/cart/detail.html
{% extends 'shop/base.html' %}
{% load i18n %}
{% load static %}

{% block title %}Shopping Cart{% endblock %}

{% block content %}
    <h1>Shopping Cart</h1>
    <table class="cart">
        <thead>
            <tr>
                <th>Image</th>
                <th>Product</th>
                <th>Quantity</th>
                <th>Remove</th>
                <th>Unit Price</th>
                <th>Price</th>
            </tr>
        </thead>
        <tbody>
            {% for item in cart %}
                {% with product=item.product %}
                    <tr>
                        <td>
                            <a href="{{ product.get_abolute_url }}">
                                <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" alt="">
                            </a>
                        </td>
                        <td>{{ product.name }}</td>
                        <td>
                            <form action="{% url 'cart:cart_add' product.id %}" method="POST">
                                {% csrf_token %}
                                {{ item.update_quantity_form.quantity }}
                                {{ item.update_qunatity_form.override }}
                                <input type="submit" value="Update">
                            </form>
                            <form action="{% url 'cart:cart_dec' product.id %}" method="POST">
                                {% csrf_token %}
                                <input type="submit" value="minus">
                            </form>
                        </td>
                        <td>
                            <form action="{% url 'cart:cart_remove' product.id %}" method="POST">
                                {% csrf_token %}
                                <input type="submit" value="remove">
                            </form>
                        </td>
                        <td class="num">₹{{ item.price }}</td>
                        <td class="num">₹{{ item.total }}</td>
                    </tr>
                {% endwith %}
            {% endfor %}
            {% if cart.coupon %}
                <tr class="subtotal">
                    <td>subtotal</td>
                    <td colspan="4"></td>
                    <td class="num">₹{{ cart.get_total_price|floatformat:2 }}</td>
                </tr>
                <tr>
                    <td>
                        "{{ cart.coupon.code }}" coupon
                        ({{ cart.coupon.discount }}% off)
                    </td>
                    <td colspan="4"></td>
                    <td class="num neg">
                        - ₹{{ cart.get_discount|floatformat:2 }}
                    </td>
                </tr>
            {% endif %}
            <tr class="total">
                <td>Total</td>
                <td colspan="4"></td>
                <td class="num">₹{{ cart.get_total_price_after_discount|floatformat:2 }}</td>
            </tr>
        </tbody>
    </table>
    {% if recommended_products %}
            <div class="recommendations cart">
                <h3>{% trans "People who bought this also bought" %}</h3>
                {% for p in recommended_products %}
                    <div class="item">
                        <a href="{{ p.get_absolute_url }}">
                            <img src="{% if p.image %}{{ p.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}">
                        </a>
                        <p><a href="{{ p.get_absolute_url }}">
                            {{ p.name }}
                        </a></p>
                    </div>
                {% endfor %}
            </div>
        {% endif %}
    <p>Apply Coupom:</p>
    <form action="{% url 'coupons:apply' %}" method="POST">
        {% csrf_token %}
        {{ coupon_apply_form }}
        <input type="submit" value="Apply">
    </form>
    <p class="text-right">
        <a href="{% url 'shop:product_list' %}" class="button light">Continue shopping</a>
        <a href="{% url 'orders:order_create' %}" class="button">Checkout</a>
    </p>
{% endblock %}